### KEYCLOAK UI ACCOUNT
POST {{auth_host}}
Content-Type: application/x-www-form-urlencoded

client_id={{auth_client_id}}&username={{auth_username}}&password={{auth_password}}&grant_type=password

> {%
    client.global.set("oauthToken", response.body.access_token)
%}

### KEYCLOAK SERICE ACCOUNT
POST {{auth_host}}
Content-Type: application/x-www-form-urlencoded

client_id={{auth_be_client_id}}&client_secret={{auth_be_client_secret}}&grant_type=client_credentials

> {%
    client.global.set("oauthTokenBe", response.body.access_token)
%}