### Coroutine

###
GET http://localhost:8080/coroutine/permissions?page=0&size=10&sort=id&direction=DESC

###
POST http://localhost:8080/coroutine/permissions
Content-Type: application/json

{"name": "test-coroutine", "description": "test description coroutine"}

###
GET http://localhost:8080/coroutine/permissions/63c55d4953a2890dbcfc4d82

###
PATCH http://localhost:8080/coroutine/permissions/63c55d4953a2890dbcfc4d82
Content-Type: application/json

{"name": "test-changed-coroutine-2", "description": "test description coroutine changed!"}

###
DELETE http://localhost:8080/coroutine/permissions/ID

### User

###
GET http://localhost:8080/coroutine/users?page=0&size=10&sort=id&direction=ASC

###
POST http://localhost:8080/coroutine/users
Content-Type: application/json

{"name": "user test coroutine", "permissionIds": ["63c55d4953a2890dbcfc4d82"]}

###
GET http://localhost:8080/coroutine/users/63c5662b7e113147cb6cb603/mapped

###
GET http://localhost:8080/coroutine/users/mapped?page=0&size=10&sort=id&direction=DESC