### Coroutine

###
GET http://localhost:8080/coroutine/permissions?page=0&size=10&sort=id&direction=DESC

###
POST http://localhost:8080/coroutine/permissions
Content-Type: application/json

{"name": "test-coroutine", "description": "test description coroutine"}

###
GET http://localhost:8080/coroutine/permissions/63c6a66e686f32099dfebd86

###
PUT http://localhost:8080/coroutine/permissions/63c6a66e686f32099dfebd86
Content-Type: application/json

{"name": "test-coroutine-changed", "description": "test description coroutine changed!"}

###
DELETE http://localhost:8080/coroutine/permissions/ID

### User

###
GET http://localhost:8080/coroutine/users?page=0&size=10&sort=id&direction=ASC

###
POST http://localhost:8080/coroutine/users
Content-Type: application/json

{"name": "user test coroutine", "email":  "test-c@test.com", "role": []}

###
PUT http://localhost:8080/coroutine/users/63c6a6c0686f32099dfebd88
Content-Type: application/json

{"name": "user test coroutine changed", "email":  "test-c@test.com", "role": ["63c6a66e686f32099dfebd86"]}

###
GET http://localhost:8080/coroutine/users/63c6a6c0686f32099dfebd88

###
DELETE http://localhost:8080/coroutine/users/63c6a6c0686f32099dfebd88
