### External Endpoint HTTP

###
GET http://localhost:8080/external/1

###
POST http://localhost:8080/external
Content-Type: application/json

{"data": "sample data node"}

###
PUT http://localhost:8080/external/1
Content-Type: application/json

{"data": "sample data node"}

###
DELETE http://localhost:8080/external/1

### NO FALLBACK
GET http://localhost:8080/external/throw-on-fallback/1