### Reactive

###
GET http://localhost:8080/reactive/permissions?page=0&size=10&sort=id&direction=DESC

###
POST http://localhost:8080/reactive/permissions
Content-Type: application/json

{"name": "test-reactive", "description": "reactive test description"}

###
GET http://localhost:8080/reactive/permissions/63c6a4b5abaf1376eafbf3e9

###
PUT http://localhost:8080/reactive/permissions/63c6a4b5abaf1376eafbf3e9
Content-Type: application/json

{"name": "test-reactive-changed", "description": "reactive test description changed!"}

###
DELETE http://localhost:8080/reactive/permissions/ID

### User

###
GET http://localhost:8080/reactive/users?page=0&size=10&sort=id&direction=ASC

###
POST http://localhost:8080/reactive/users
Content-Type: application/json

{"name": "reactive user test", "email":  "test@test.com", "role": ["a63c6a4b5abaf1376eafbf3e9"]}

###
PUT http://localhost:8080/reactive/users/63c6a507abaf1376eafbf3ea
Content-Type: application/json

{"name": "reactive user test changed", "email":  "test@test.com", "role": ["63c6a4b5abaf1376eafbf3e9"]}

###
GET http://localhost:8080/reactive/users/63c6a507abaf1376eafbf3ea

###
GET http://localhost:8080/reactive/users/unmapped?page=0&size=10&sort=id&direction=DESC

###
DELETE http://localhost:8080/reactive/users/63c6a507abaf1376eafbf3ea
