### Sample Endpoint HTTP

###
GET {{host}}/sample/{{$random.integer(0, 1000)}}

###
POST {{host}}/sample
Content-Type: application/json

{"data": "sample data: {{$uuid}}"}

###
PUT {{host}}/sample/{{$random.integer(0, 1000)}}
Content-Type: application/json

{"data": "sample data: {{$uuid}} change"}

###
DELETE {{host}}/sample/{{$random.integer(0, 1000)}}


## Secured

###
GET {{host}}/sample-secured/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}

###
POST {{host}}/sample-secured
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"data": "sample data: {{$uuid}}"}

###
PUT {{host}}/sample-secured/{{$random.integer(0, 1000)}}
Content-Type: application/json
Authorization: Bearer {{oauthToken}}

{"data": "sample data: {{$uuid}} change"}

###
DELETE {{host}}/sample-secured/{{$random.integer(0, 1000)}}
Authorization: Bearer {{oauthToken}}
